ALTER TABLE companies
    ADD COLUMN IF NOT EXISTS safer_name VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS safer_dba_name VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS safer_address VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS safer_city VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS safer_zip VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS safer_state VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS safer_active SMALLINT NULL,
    ADD COLUMN IF NOT EXISTS safer_is_broker SMALLINT NULL;
